name: Python Package using Conda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: moose
    - name: Setup conda channels
      run: |
        conda config --add channels https://conda.software.inl.gov/public
        conda install mamba -n base -c conda-forge
    - name: Install dependencies 
      run: |
        mamba install moose-tools moose-libmesh
