name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: https://conda.software.inl.gov/public,conda-forge,defaults
        channel-priority: true
        activate-environment: moose
    - name: Install dependencies 
      shell: bash -l {0}
      run: |
        mamba init
        conda activate moose
        mamba install moose-tools moose-libmesh
    - name: Install MOOSE
      shell: bash -l {0}
      run: |
        cd ..
        git clone https://github.com/aladshaw3/moose.git
        cd moose
        git checkout master
        cd test
        conda activate moose
        make -j4
    - name: Run MOOSE Tests
      shell: bash -l {0}
      run: | 
        conda activate moose
        ./run_tests -j4
