name: Python Package using Conda

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: moose
    - name: Setup conda channels
      run: |
        conda config --add channels https://conda.software.inl.gov/public
    - name: Install dependencies 
      run: |
        conda install moose-tools 
        conda install moose-libmesh
