name: Python Package using Conda

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: https://conda.software.inl.gov/public,conda-forge,defaults
        channel-priority: true
        activate-environment: moose
        #environment-file: etc/example-environment.yml
    #- name: Setup conda channels
    #  run: |
    #    conda config --add channels https://conda.software.inl.gov/public
    - name: Install dependencies 
      run: |
        mamba install moose-tools moose-libmesh
