name: MAC-MOOSE Master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 5 * * 5'

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v3
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: https://conda.software.inl.gov/public,conda-forge,defaults
        channel-priority: true
        activate-environment: moose
    - name: Install dependencies
      run: |
        mamba init
        conda activate moose
        mamba install moose-tools moose-libmesh
    - name: Install MOOSE
      run: |
        cd ..
        git clone https://github.com/idaholab/moose.git
        cd moose
        git checkout master
        cd test
        conda activate moose
        make -j4
#    - name: Run MOOSE Tests
#      shell: bash -l {0}
#      run: |
#        conda activate moose
#        cd ..
#        cd moose/test
#        ./run_tests -j4
    - name: Build CATS
      run: |
        conda activate moose
        make -j4
    - name: Run CATS Tests
      run: |
        conda activate moose
        ./run_tests -j4
